// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6A02i2wlcxW-WepVcXnZCloADjFiGMOg',
    appId: '1:533766237617:web:ae0478a994be04d2df6190',
    messagingSenderId: '533766237617',
    projectId: 'encryption-algorithm-analysis',
    authDomain: 'encryption-algorithm-analysis.firebaseapp.com',
    databaseURL: 'https://encryption-algorithm-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'encryption-algorithm-analysis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtl_AfRoQzwujG5Te7cOX3A0vAspouY00',
    appId: '1:533766237617:android:c9983d82675ce12cdf6190',
    messagingSenderId: '533766237617',
    projectId: 'encryption-algorithm-analysis',
    databaseURL: 'https://encryption-algorithm-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'encryption-algorithm-analysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp9MohXS26BurdDgZcO2UT43YQyHGQ6wI',
    appId: '1:533766237617:ios:6a89b29248eae36bdf6190',
    messagingSenderId: '533766237617',
    projectId: 'encryption-algorithm-analysis',
    databaseURL: 'https://encryption-algorithm-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'encryption-algorithm-analysis.appspot.com',
    iosBundleId: 'com.example.encryptionAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp9MohXS26BurdDgZcO2UT43YQyHGQ6wI',
    appId: '1:533766237617:ios:6a89b29248eae36bdf6190',
    messagingSenderId: '533766237617',
    projectId: 'encryption-algorithm-analysis',
    databaseURL: 'https://encryption-algorithm-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'encryption-algorithm-analysis.appspot.com',
    iosBundleId: 'com.example.encryptionAnalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6A02i2wlcxW-WepVcXnZCloADjFiGMOg',
    appId: '1:533766237617:web:78bc3f47ca5db189df6190',
    messagingSenderId: '533766237617',
    projectId: 'encryption-algorithm-analysis',
    authDomain: 'encryption-algorithm-analysis.firebaseapp.com',
    databaseURL: 'https://encryption-algorithm-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'encryption-algorithm-analysis.appspot.com',
  );

}